# Use the official Logstash image
FROM docker.elastic.co/elasticsearch/elasticsearch:8.15.1

# Copy the Logstash configuration file to the container
COPY ./config/elasticsearch.yml /usr/share/elasticsearch/config/elasticsearch.yml
